const { DataTypes } = require('sequelize');
const sequelize = require('../db');

const Proposal = sequelize.define('Proposal', {
  userId:             { type: DataTypes.INTEGER },
  category:           { type: DataTypes.STRING },
  proposalTitle:      { type: DataTypes.STRING },
  studentName:        { type: DataTypes.STRING },
  studentId:          { type: DataTypes.STRING },
  department:         { type: DataTypes.STRING },
  academicYear:       { type: DataTypes.STRING },
  projectType:        { type: DataTypes.STRING },
  duration:           { type: DataTypes.STRING },
  introduction:       { type: DataTypes.TEXT },
  problemStatement:   { type: DataTypes.TEXT },
  objectives:         { type: DataTypes.TEXT },
  scopeOfWork:        { type: DataTypes.TEXT },
  methodologies:      { type: DataTypes.TEXT },
  tools:              { type: DataTypes.TEXT },
  teamComposition:    { type: DataTypes.STRING },
  expectedOutcome:    { type: DataTypes.TEXT },
  futureEnhancements: { type: DataTypes.TEXT },
  references:         { type: DataTypes.TEXT },
  status:             { type: DataTypes.STRING, defaultValue: 'pending' },
  submittedAt:        { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  programmeName:      { type: DataTypes.STRING },
  submittedBy:        { type: DataTypes.STRING },
  designation:        { type: DataTypes.STRING },
  submissionDate:     { type: DataTypes.STRING },
  submittedTo:        { type: DataTypes.STRING },
  aboutProgramme:     { type: DataTypes.TEXT },
  eligibility:        { type: DataTypes.TEXT },
  programmeFee:       { type: DataTypes.TEXT },
  objectives1:        { type: DataTypes.TEXT },
  benefits:           { type: DataTypes.TEXT },
  programmeOutcomes:  { type: DataTypes.TEXT },
  assessmentNotes:    { type: DataTypes.TEXT },
  coordinatorResp:    { type: DataTypes.TEXT },
  selectionProcess:   { type: DataTypes.TEXT },
  infrastructure:     { type: DataTypes.TEXT },
  budgetNotes:        { type: DataTypes.TEXT },
  syllabusCourses:    { type: DataTypes.TEXT },
});

module.exports = Proposal;